### ISSUE TITLE
解盘|求解工作 婚姻

### ISSUE THREAD

**Issue by HiJackXD** [SylarLong/iztro#100]
https://ziwei.pub/astrolabe/?d=1990-8-1&t=10&leap=false&g=male&type=solar

出生地在自贡，目前成都定居，单身。准备换城市了，目前考虑北京。 盘已考虑太阳时。感谢🙏

**Comment by HiJackXD** [comment]
> 我这边不需要真太阳时哦，请转换回钟表时间 @HiJackXD

以前我也不太清楚自己时间，不过对比了前后时辰，就目前链接里这个最符合我状况。感谢

**Comment by SylarLong** [comment]
@HiJackXD 

如果是你提供的链接的话，命宫主星是 `太阳天梁` 组成的 `日照雷门` 格，但由于是空宫借星形成的，所以没有享受到日照雷门格的好处。从你盘上看你成长过程比较辛苦，坎坷比较多。你属于奉献型人格，对朋友非常仗义，这也让你的圈子里充满了各种各样能力很强，条件很好的人。在我学习的紫微斗数体系里，是没有 `方位` 这个概念的，所以我不能对你前往哪个城市发展给出建议，但是你是适合离乡发展的。记得做决策的适合要改掉一点就燃，说风就是雨的个性。

个性推演如果差异比较大的话，请参阅 [为什么星盘显示的个性和实际个性差那么多？](https://github.com/SylarLong/iztro/discussions/122)

**Comment by HiJackXD** [comment]
谢谢 挺准的🤓
