### ISSUE TITLE
解盘申请

### ISSUE THREAD

**Issue by Cat7373** [SylarLong/iztro#101]
### 星盘信息
![image](https://github.com/SylarLong/iztro/assets/9296576/c13fdca9-7994-4cad-a57a-1ee38f4ca568)
![image](https://github.com/SylarLong/iztro/assets/9296576/61811fe4-9d0a-48a7-a6d8-0c065afafa34)

### 时辰是否准确

- [x] 是
- [ ] 大概准确
- [ ] 不确定

### 咨询问题
1. 我这个夫妻宫还有没有救喵
2. 随缘啦，看到啥捎带讲讲嘛喵
3. 与 https://github.com/SylarLong/iztro/issues/97 重复，因对应 Issue 有三个人回复了不同盘，我就不主动关掉它了 hhh

**Comment by SylarLong** [comment]
@Cat7373 

盘上看你是个玩家，喜欢享受，玩乐~异性缘很好，社交属性很强。但很可能也是因为这些属性，导致你感情上烦恼颇多。父母脾气都不错，但看起来你会觉得父母碎碎念，管得宽。你是一个自我意识非常强的人，有些自负，也有些文青~其他都挺好的，就是手太散，存不住钱。

仅供参考，不准勿怪，请参阅 [Wiki](https://github.com/SylarLong/iztro/wiki/%E4%B8%BA%E4%BB%80%E4%B9%88%E6%98%9F%E7%9B%98%E6%98%BE%E7%A4%BA%E7%9A%84%E4%B8%AA%E6%80%A7%E5%92%8C%E6%88%91%E5%AE%9E%E9%99%85%E4%B8%AA%E6%80%A7%E5%B7%AE%E9%82%A3%E4%B9%88%E5%A4%9A%EF%BC%9F)
