### ISSUE TITLE
解盘申请

### ISSUE THREAD

**Issue by er567** [SylarLong/iztro#102]
### 时辰是否准确

- [√] 是
- [ ] 大概准确
- [ ] 不确定

### 咨询问题

事业，家庭，财运

**Comment by SylarLong** [comment]
@er567 

盘上看你是兼具社交和执行的个性，倔强、刚直。如果改掉过于爱钻牛角尖的性格，你会发现更广阔的天地。你聪明但不好学，朋友多但帮助小，因为你有点事必躬亲的感觉，凡事总觉得要自己做才放心~事业上管理属性蛮强的，但还是那个问题，如果要走管理层，你需要懂得放权，把合适的事情交给合适的人去做，不要做独行侠。财务上，不管是理财还是消费，你都属于冲动型。

仅供参考，不准勿怪，请参阅 [Wiki](https://github.com/SylarLong/iztro/wiki/%E4%B8%BA%E4%BB%80%E4%B9%88%E6%98%9F%E7%9B%98%E6%98%BE%E7%A4%BA%E7%9A%84%E4%B8%AA%E6%80%A7%E5%92%8C%E6%88%91%E5%AE%9E%E9%99%85%E4%B8%AA%E6%80%A7%E5%B7%AE%E9%82%A3%E4%B9%88%E5%A4%9A%EF%BC%9F)

**Comment by er567** [comment]
谢谢
