### ISSUE TITLE
解盘申请|婚姻|工作

### ISSUE THREAD

**Issue by skrlst** [SylarLong/iztro#103]
婚姻、工作

[星盘链接](https://ziwei.pub/astrolabe/?d=1998-06-04&t=12&leap=false&g=male&type=lunar)

![1](https://github.com/SylarLong/iztro/assets/70947084/5529ae99-94d1-4ee2-8042-99ae8676f528)

**Comment by skrlst** [comment]
## 时辰是否准确
 是

## 咨询问题

婚姻
工作

**Comment by GibuAuja** [comment]
![image](https://github.com/SylarLong/iztro/assets/53562605/e6f00ad7-e748-4858-a838-2995976836bd)

**Comment by SylarLong** [comment]
@skrlst 

你命宫主星是 [天相星](https://www.ziwei.pro/learn/major-star.html#%E5%A4%A9%E7%9B%B8%E6%98%9F)，这是一颗很擅长与人打交道的星耀，从你盘上看，你文章也应该写得不错。情感丰富，对另一半要求很高，注意三角恋问题。工作方面你却少规划，比较容易换工作，颇有些事倍功半的意思。这可能和你遇事有些急躁，耐心不足有关系。利用好你的社交技能，选好一个赛道深耕下去，还是挺不错的，发挥好你的组织和管理才能，做事有点韧性，就好了。

个性推演如果差异比较大的话，请参阅 [为什么星盘显示的个性和实际个性差那么多？](https://github.com/SylarLong/iztro/discussions/122)

**Comment by SylarLong** [comment]
@GibuAuja 

你命宫主星是 [七杀星](https://www.ziwei.pro/learn/major-star.html#%E4%B8%83%E6%9D%80%E6%98%9F)，这个盘兼具 `杀破狼` 格和 `七杀朝斗` 格，拥有这两个格局的你，必定是个性刚强，言出必行的人。因为你没有说明想要了解哪方面的情况，我就先做个性格推演。你的这个格局却少亲和力，给人感觉气场十足，你还是个非常会推销自己的人。杀破狼的人不甘平凡，所以你的这个盘注定会有个精彩的人生。

个性推演如果差异比较大的话，请参阅 [为什么星盘显示的个性和实际个性差那么多？](https://github.com/SylarLong/iztro/discussions/122)
