### ISSUE TITLE
解盘申请｜健康 财运 儿女 注意事项，感谢！

### ISSUE THREAD

**Issue by lidutech** [SylarLong/iztro#107]
### 星盘信息

[
](https://ziwei.pub/astrolabe/?d=1986-5-24&t=9&leap=false&g=male&type=solar)
### 时辰是否准确

- [✔ ] 是
- [ ] 大概准确
- [ ] 不确定

### 咨询问题

1. 财运如何？未来财运在哪些年份或者年份段较好？
2. 个人健康状况如何？
3. 子女未来成长及健康如何？
4. 是否有注意事项
5. 感谢！
6. star 三连！

**Comment by SylarLong** [comment]
@lidutech 你没有贴星盘图片哦

**Comment by SylarLong** [comment]
@lidutech 

厉害，你这个贴盘的方式该推广，哈哈。阁下的命宫主星是 [破军星](https://www.ziwei.pro/learn/major-star.html#%E7%A0%B4%E5%86%9B%E6%98%9F)，从你的盘上看，你有点丢三落四情况。 喜欢交友，所以朋友多，社交广。行为上想得多，做得少，恒心不足，难以持之以恒的去做一件事情。健康状态的话，视力、肝、肠胃是你的弱项，需要格外保护。在子女方面，你小孩很有主见，聪明机灵，但是你不要过度溺爱，解放天性让他成长就会不错，这个是从你的盘角度来看的，相当于从你的视角看TA，如果要看子女还是要用子女的盘看才会更加客观。财运上，建议你谨慎投资，你并不擅长理财和玩金融游戏，也不太适合做生意，所以你不理财，财就不会离开你。

个性推演如果差异比较大的话，请参阅 [为什么星盘显示的个性和实际个性差那么多？](https://github.com/SylarLong/iztro/discussions/122)
