### ISSUE TITLE
解盘申请

### ISSUE THREAD

**Issue by GibuAuja** [SylarLong/iztro#109]
### 星盘信息
![image](https://github.com/SylarLong/iztro/assets/53562605/2d6a3a2b-3e0d-4ac2-8b30-0ad00e86f8e4)

### 时辰是否准确

- [ ] 是
- [ √] 大概准确
- [ ] 不确定

### 咨询问题
姻缘，事业，家庭

请大佬帮忙看一下：姻缘，事业，家庭

**Comment by SylarLong** [comment]
@GibuAuja 

由于你不太确定自己的时间，我只能以你发出的盘进行一下性格推演，如果性格推演结果和你本身个性相去甚远的话，其他信息就可以忽略不看了。盘上看，你的命宫主星是 [七杀星](https://ziwei.pro/learn/major-star.html#%E4%B8%83%E6%9D%80%E6%98%9F)，这颗星耀个性耿直，不喜欢花里胡哨绕弯子的事情，要小心成为书呆子个性哦。情感依赖比较重，不喜欢小孩子，或者不太会和小孩子相处。喜欢社交，但是另一半会干涉你的社交。你不服输，不怕失败的个性在工作中还是能得到大家欣赏的，如果工作中能主动多承担一些，少一点计较，会对你事业上帮助更大。

仅供参考，不准勿怪，请参阅 [WIKI](https://github.com/SylarLong/iztro/discussions/122)

**Comment by SylarLong** [comment]
忘记说家庭了，看起来你经常不着家，但是心里是装着对家庭的责任的，挺好的。
