### ISSUE TITLE
解盘申请

### ISSUE THREAD

**Issue by glIrving** [SylarLong/iztro#110]
### 星盘信息

![QQ截图20231120164759](https://github.com/SylarLong/iztro/assets/65054910/2108eb57-bc27-4784-9602-9df4f8dd7e88)

### 时辰是否准确

- [x] 是

### 咨询问题

1帮分析下整体盘面 主要想问财运和事业 
2如果买车的话 23年或者24年什么时间合适

**Comment by glIrving** [comment]
![Uploading QQ截图20231120164759.png…]()

**Comment by SylarLong** [comment]
@glIrving 

从你盘上看，你应该是个不信命的理性派，可能来此只是娱乐一番。阁下命宫主星是 [破军星](https://ziwei.pro/learn/major-star.html#%E7%A0%B4%E5%86%9B%E6%98%9F) ，杀破狼的格局的破军星让你身上背着一身的“反骨”，你喜欢打破既定规则，让事情按照自己既定的目标去走，不喜欢走被人安排好的路~ 才财务上你还是比较善于和金钱打交道的，收支用度都在你的计算掌握之中。固执和不太讨喜的说方式容易让你失去一些朋友，但是你对朋友还是挺仗义的。至于你说的买车问题，理论上讲你什么时候条件允许什么时候买都是可以的，但是如果看是否容易买到有问题的车，就可以参考一下，24年没问题，条件挺好的。

仅供参考，不准勿怪，请参阅 [WIKI](https://github.com/SylarLong/iztro/discussions/122)
