### ISSUE TITLE
大佬，解盘申请

### ISSUE THREAD

**Issue by Li-mengbo** [SylarLong/iztro#111]
### 星盘信息
https://sm.ms/image/1HIQl3MS7ygbokp

### 时辰是否准确

是

### 咨询问题

- 财运如何？未来财运在哪些年份或者年份段较好？
- 个人健康状况如何？
- 子女未来成长及健康如何？
- 是否有注意事项
- 家庭如何？

**Comment by Li-mengbo** [comment]
谢谢大佬

**Comment by SylarLong** [comment]
不客气
