### ISSUE TITLE
解盘申请

### ISSUE THREAD

**Issue by 8824PPZ** [SylarLong/iztro#114]
### 星盘信息

![image](https://github.com/SylarLong/iztro/assets/36729296/dba36c91-a931-49bd-b2d0-89a60887cf84)

### 时辰是否准确

- [ ] 是
- [ √] 大概准确
- [ ] 不确定

### 咨询问题

婚姻、事业、财运  

大佬看下啥时候可能会结婚

**Comment by 8824PPZ** [comment]
目前还是单身。

**Comment by SylarLong** [comment]
以盘上信息：

> 啥时候可能会结婚

2025年

> 婚姻

较为不会处理感情，存在沟通问题。你个性急躁但好在听劝。把夫妻关系处成兄弟朋友，就可以了。

> 事业

有点工作狂，喜欢研究，但是在工作中有点阻力。你想快点完成的事情通常会有扯后腿的情况发生。但总体还不错，放慢自己的节奏，去把每一个细节做好。大事可成。

> 财运

有理财天赋的，财运上没太大问题，理财观和消费观都还不错。

**Comment by 8824PPZ** [comment]
> 以盘上信息：
> 
> > 啥时候可能会结婚
> 
> 2025年
> 
> > 婚姻
> 
> 较为不会处理感情，存在沟通问题。你个性急躁但好在听劝。把夫妻关系处成兄弟朋友，就可以了。
> 
> > 事业
> 
> 有点工作狂，喜欢研究，但是在工作中有点阻力。你想快点完成的事情通常会有扯后腿的情况发生。但总体还不错，放慢自己的节奏，去把每一个细节做好。大事可成。
> 
> > 财运
> 
> 有理财天赋的，财运上没太大问题，理财观和消费观都还不错。

那夫妻关系是不是很差，经常会吵架的那种？

**Comment by SylarLong** [comment]
@8824PPZ 能吵架都算沟通了，容易冷战

**Comment by 8824PPZ** [comment]
> @8824PPZ 能吵架都算沟通了，容易冷战

这。。。好吧，多谢大佬指点。我感觉我都不想结婚了。。

**Comment by SylarLong** [comment]
@8824PPZ 知道了情况就该去调整啊，不是让你逃避的

**Comment by 8824PPZ** [comment]
> @8824PPZ 知道了情况就该去调整啊，不是让你逃避的

嗯，好的。谢谢
