### ISSUE TITLE
解盘申请

### ISSUE THREAD

**Issue by nasa1024** [SylarLong/iztro#116]
### 星盘信息

![image](https://github.com/SylarLong/iztro/assets/28981872/5dacbb78-4e12-4c7b-ac94-f9b41e3d1947)
https://ziwei.pub/astrolabe/?d=1996-5-20&t=8&leap=false&g=male&type=solar

### 时辰是否准确

- [x] 是
- [ ] 大概准确
- [ ] 不确定

### 咨询问题
* 财运（事业）
    * 多少岁才能自由一点（前几年做交易亏了太多了）
* 婚姻
   * 还会不会有坎坷（已经和对象快结婚了）

**Comment by SylarLong** [comment]
@nasa1024 
这是一个善于思考，想法天马行空，但有还有点逻辑思维能力的人。很聪明，笑脸迎人，就是有点懒，追求精神享受，执行力比较差。

> 财运
对理财判断能力较差，如果经商或者玩金融有点赔本赚吆喝的意思。理财上，建议以长线风险小的产品为主，尽量不要接触短线投机。35岁以后走田宅大限会比较用心的赚钱，建议主副业一起，主业求稳，副业求变（仅供参考，不做投资建议）

> 事业
颇有事业心，虽然执行能力不足但是比较容易产生做副业的想法。工作中注意合同问题。

> 婚姻
近期感情无碍，但感情是比较复杂的，从长远看，你在感情方面的热情比较难保持，还是需要用心经营。对象很漂亮，祝百年好合。
