### ISSUE TITLE
解盘申请

### ISSUE THREAD

**Issue by liuxiaoqigui** [SylarLong/iztro#117]
### 星盘信息
https://ziwei.pub/astrolabe/?d=1994-12-3&t=4&leap=false&g=male&type=solar

### 时辰是否准确

- [ ✔️] 是
- [ ] 大概准确
- [ ] 不确定

### 咨询问题

财运以后会好吗 以后会不会有钱

**Comment by liuxiaoqigui** [comment]
子女身体学业怎么样

**Comment by SylarLong** [comment]
@liuxiaoqigui 

如果时间没错的话，你这个明日驱暗格虽然太阳星力量不足，但是整体还不错。辛劳一点也劳有所得。天盘财运是不错的，可以说如果阻碍比较少。不过要记得止盈，不要贪多。至于你说会不会有钱，上帝给了你尺寸还不算小的桶，能装多少，就看你自己了。
