### ISSUE TITLE
解盘申请

### ISSUE THREAD

**Issue by MagicConchCpp** [SylarLong/iztro#118]
[###](url) 星盘信息

https://ziwei.pub/astrolabe/?d=1998-03-07&t=5&leap=false&g=male&type=lunar

### 时辰是否准确
- [ x ] 是
- [ ] 大概准确
- [ ] 不确定

### 咨询问题
工作情况、定居点、婚姻、身体健康情况

谢谢大佬们

**Comment by SylarLong** [comment]
@MagicConchCpp 

- 工作/财运情况
  事业方面想得多，做得少，或是让你感觉收入和付出有不小差距。有点赚四方财的意思，如果有项目可以尝试一下。

- 定居点
  这个非常抱歉，我不会

- 婚姻
- 身体健康状况
  注意骨骼、关节方面的问题。（仅供参考）
