### ISSUE TITLE
解盘申请

### ISSUE THREAD

**Issue by justingcode** [SylarLong/iztro#120]
### 星盘信息

(https://ziwei.pub/astrolabe/?d=1993-7-25&t=2&leap=false&g=male&type=solar)

### 时辰是否准确

- [ v] 是
- [ ] 大概准确
- [ ] 不确定

### 咨询问题

事业，是否要跳槽或者换城市

**Comment by SylarLong** [comment]
https://github.com/SylarLong/iztro/discussions/151
