### ISSUE TITLE
解盘申请

### ISSUE THREAD

**Issue by EroQingNian** [SylarLong/iztro#121]
### 星盘信息

![image](https://github.com/SylarLong/iztro/assets/51228085/d77da6b7-bd10-478f-be09-f8cde0b22d96)

### 时辰是否准确

- [x] 是
- [ ] 大概准确
- [ ] 不确定

### 咨询问题

修改下提问：
我是否是适合做生意？
我未来伴侣是什么性格？
我将来和伴侣相处得怎样?

**Comment by SylarLong** [comment]
https://github.com/SylarLong/iztro/discussions/151
