### ISSUE TITLE
解盘申请

### ISSUE THREAD

**Issue by balckduck** [SylarLong/iztro#123]
### 星盘信息

https://ziwei.pub/astrolabe/?d=1997-6-26&t=7&leap=false&g=male&type=solar

### 时辰是否准确

- [✅ ] 是
- [ ] 大概准确
- [ ] 不确定

### 咨询问题
未来3年的财运,官运是？

**Comment by SylarLong** [comment]
https://github.com/SylarLong/iztro/discussions/151
