### ISSUE TITLE
解盘申请

### ISSUE THREAD

**Issue by whoCan1** [SylarLong/iztro#132]
### 星盘信息
![image](https://github.com/SylarLong/iztro/assets/9334705/5fef63cc-3710-4559-a640-b4f8c72cda37)

### 时辰是否准确

- [ √] 是
- [ ] 大概准确
- [ ] 不确定

### 咨询问题
想咨询一下事业，婚姻和子女

**Comment by SylarLong** [comment]
https://github.com/SylarLong/iztro/discussions/151
