### ISSUE TITLE
解盘申请

### ISSUE THREAD

**Issue by xiongminghui** [SylarLong/iztro#133]
### 星盘信息

![1700641624864](https://github.com/SylarLong/iztro/assets/20530068/83de1280-9b1c-4e5a-99af-d5f449c6fb8b)

### 时辰是否准确

- [ ✅] 是
- [ ] 大概准确
- [ ] 不确定

### 咨询问题

未来几年的运势

**Comment by SylarLong** [comment]
https://github.com/SylarLong/iztro/discussions/151
