### ISSUE TITLE
解盘申请

### ISSUE THREAD

**Issue by echouname** [SylarLong/iztro#138]
### 星盘信息

[星盘链接](https://ziwei.pub/astrolabe?d=1994-12-1&t=8&leap=false&g=male&type=solar)

### 时辰是否准确

- [✅ ] 是
- [ ] 大概准确
- [ ] 不确定

### 咨询问题

事业、婚姻、财运

**Comment by SylarLong** [comment]
https://github.com/SylarLong/iztro/discussions/151
