### ISSUE TITLE
出生时间不能选择18xx年

### ISSUE THREAD

**Issue by jazzg62** [SylarLong/iztro#139]
### 描述（Description）

出生时间不能选择18xx年

### 重现（Reproduce）

![2023](https://github.com/SylarLong/iztro/assets/30382988/33457b41-57d5-405d-843d-eaf18a6085bb)

**Comment by SylarLong** [comment]
是的，由于阳历转农历算法数据的限制，只支持1900-2-1到2100-12-31之间的日期。
