### ISSUE TITLE
真太陽時間校正

### ISSUE THREAD

**Issue by limehead** [SylarLong/iztro#140]
### 摘要（Summary）

🇨🇳

因為經度產生時差的問題，會讓我們以為生日當時紀錄的時間是正確的。例如，在台北同一時間在重慶出生的人，雖然行政時間是一樣的，但是其實已經有很巨大的時差。真太陽時間就是在進行這個與中原標準時間的校正，這樣就可以進行全球東西半球正確的紫微斗數的排盤。

**Comment by SylarLong** [comment]
其实我个人是不太提倡用真太阳时排盘的，我记得鄒信軫老师也说过不需要转真太阳时。iztro旨在提供一个紫微斗数命盘信息输出功能，对于传入的时间可以由开发者自行添加真太阳时转换功能后将转换后的时间传入iztro。感谢您的建议～ 👍  happy coding~ 🎉
