### ISSUE TITLE
解盘申请

### ISSUE THREAD

**Issue by SUNFei1126** [SylarLong/iztro#141]
### 星盘信息

<img width="1384" alt="image" src="https://github.com/SylarLong/iztro/assets/28339082/dc3e29e2-7070-4344-8616-e87edd383db7">

### 时辰是否准确

- [✔️ ] 是
- [ ] 大概准确
- [ ] 不确定

### 咨询问题

1.未来几年的运势
2. 是否有财运？感觉自己没有财运
3. 定居点，这几年在考虑换城市工作
4. 婚姻

**Comment by SylarLong** [comment]
https://github.com/SylarLong/iztro/discussions/151
