### ISSUE TITLE
解盘申请

### ISSUE THREAD

**Issue by weibocy** [SylarLong/iztro#144]
### 星盘信息

https://ziwei.pub/astrolabe/?d=1990-6-27&t=3&leap=false&g=male&type=solar
![ziwei pub-iztrolabe](https://github.com/SylarLong/iztro/assets/74368831/7c2892fc-bbad-467c-851e-da8b34a6e16b)

### 时辰是否准确

- [ ✔] 是
- [ ] 大概准确
- [ ] 不确定

### 咨询问题

个人一生运势如何？将在哪个阶段起势？
个人健康问题如何？哪些方面需要额外注意？
婚姻问题，何时会有桃花及何时会结婚（目前还未结婚）
工作方面今年感觉不得志，来年或者后续是否有转机？
财运如何，财运和理财之间的关系如何
是否有其他注意事项
感谢！！！！！

**Comment by SylarLong** [comment]
https://github.com/SylarLong/iztro/discussions/151
