### ISSUE TITLE
请问什么时候出手机版本？

### ISSUE THREAD

**Issue by swingpon** [SylarLong/iztro#146]
### 摘要（Summary）

🇨🇳

🇺🇸

---

Ref. {referrence}

#### 需求（Requirements）

🇨🇳
- 需求一
- 需求二
- ...

🇺🇸
- feature 1
- feature 2
- ...

**Comment by SylarLong** [comment]
@swingpon 
iztro只是生成排盘数据的库，你可以在任何支持js的环境下面使用的
