### ISSUE TITLE
解盘申请

### ISSUE THREAD

**Issue by zhouzhiguang2020** [SylarLong/iztro#147]
### 星盘信息

![1702694618058](https://github.com/SylarLong/iztro/assets/13230243/995d9212-ab8b-4106-af44-a76b1430b1a5)

### 时辰是否准确

- [ *] 是
- [ ] 大概准确
- [ ] 不确定

### 咨询问题

财运和婚姻问题

**Comment by SylarLong** [comment]
https://github.com/SylarLong/iztro/discussions/151
