### ISSUE TITLE
运行文档的代码报错 Cannot read properties of undefined (reading 'bySolar')

### ISSUE THREAD

**Issue by XiaoIsGood** [SylarLong/iztro#148]
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>iztro-紫微斗数开源库</title>
  </head>
  <body>
    <script src="https://cdn.jsdelivr.net/npm/iztro/dist/iztro.min.js"></script>
    <script>
      // 获取一张星盘数据
      var astrolabe = iztro.asto.bySolar('2000-8-16', 2, '男', true, 'zh-CN');
    </script>
  </body>
</html>

**Comment by SylarLong** [comment]
@XiaoIsGood 
抱歉，是文档中的一处拼写错误。
AS IS 
`iztro.asto.bySolar`

TO BE
`iztro.astro.bySolar`
