### ISSUE TITLE
v2.0.7:排盘-天梁星在申宫亮度错误

### ISSUE THREAD

**Issue by crimsonskyrem** [SylarLong/iztro#166]
### 描述（Description）

天梁星在申宫时，亮度应为陷，排出来的亮度是庙

### 版本（Version）

- v2.0.7

### 环境（Environment）

网页

### 重现（Reproduce）

- 调用的方法（funciton name）

[链接](https://ziwei.pub/astrolabe/?d=2023-01-03&t=5&g=male&type=solar)

- 参数（parameters）

  

- 返回值（returns)

**Comment by SylarLong** [comment]
感谢指出~应该是 cv 问题 👍

**Comment by crimsonskyrem** [comment]
> 感谢指出~应该是 cv 问题 👍

感觉其他星的亮度似乎也有偏差，请问 @SylarLong  是参考的什么地方？

**Comment by SylarLong** [comment]
> > 感谢指出~应该是 cv 问题 👍
> 
> 感觉其他星的亮度似乎也有偏差，请问 @SylarLong 是参考的什么地方？

参考的紫微斗数全书。不过我当时偷懒用ctrl C ctrl V比较多。可能留下了一些坑，感谢指正，我会回去核对一遍的。

**Comment by SylarLong** [comment]
@crimsonskyrem 问题已修复，请更新版本到2.2.3。再次感谢
