### ISSUE TITLE
{version}:{function}-年龄和生肖  好像有问题

### ISSUE THREAD

**Issue by huowanqing** [SylarLong/iztro#170]
![1706061949562](https://github.com/SylarLong/iztro/assets/42835536/b8fec777-8dfc-4d77-b5c7-b7310f56aabf)

**Comment by SylarLong** [comment]
@huowanqing 子年属鼠没有问题哦。年龄的话这个地方是按虚岁来，你输入生日的农历是腊月二十一，当前是腊月十四，还没有过生日哦，如果把运限时间调到腊月十五以后，年龄就对了。感谢关注~
