### ISSUE TITLE
生肖是不是有问题？

### ISSUE THREAD

**Issue by shawon1220** [SylarLong/iztro#171]
![image](https://github.com/SylarLong/iztro/assets/10345404/c42d950e-dfe0-4bf4-bfd9-12c33854bc78)

**Comment by SylarLong** [comment]
@shawon1220 你好，紫微斗数是以立春为分割点的，生肖跟着年柱的地支走的，经查询1984年腊月十五就立春了，立春之后就是乙丑年，所以是没有问题的哦。这个可能和其他以初一为分割点的有所区别。

**Comment by shawon1220** [comment]
哦，那我这是属牛么，一直认为自己属鼠

**Comment by SylarLong** [comment]
> 哦，那我这是属牛么，一直认为自己属鼠

关于生肖，有两个说法，传统的是以立春算，但是后来也有以正月初一算的，所以属牛属鼠都不算错~
