### ISSUE TITLE
星辰排布

### ISSUE THREAD

**Issue by JohnnyWaterGitHub** [SylarLong/iztro#174]
### 摘要（Summary）

🇨🇳
看着很别扭，为什么不是竖着排，从右到左的顺序，这个排盘的布局还得自己实现吗，底层调上来的星辰得转换成竖着吗

**Comment by SylarLong** [comment]
@JohnnyWaterGitHub iztro只是一个获取数据和判断的接口，https://ziwei.pub 是一个示例站，具体布局方式可以根据自己的喜好自行实现哦
