### ISSUE TITLE
[2.4.1]: Wrong results using the parameter yearDivide to 'normal'

### ISSUE THREAD

**Issue by ameurenand** [SylarLong/iztro#190]
### 描述（Description）

With version 2.2.1, everything is correct.
But with version 2.4.1, I have some wrong results using the configuration parameter yearDivide to 'normal'.

### Example of incorrect palace's decade range : 

- Using iztro version 2.2.1 (expected result):
```
const astrolabe = astro.bySolar('1980-2-14', 0, 'male', true, 'en-US');
console.log(astrolabe.palaces[0].decadal.range);     // [112, 121]
```

- Using iztro version 2.4.1 (wrong result):
```
astro.config({yearDivide: 'normal'});
const astrolabe = astro.bySolar('1980-2-14', 0, 'male', true, 'en-US');
console.log(astrolabe.palaces[0].decadal.range);     // [12, 21]
```

### Example of incorrect earthly branch of the year : 

- Using iztro version 2.2.1 (expected result):
```
const astrolabe = astro.bySolar('1980-2-14', 0, 'male', true, 'en-US');
const horoscope = astrolabe.horoscope('1980-2-14');
console.log(horoscope.yearly.earthlyBranch);     // wei
```

- Using iztro version 2.4.1 (wrong result):
```
astro.config({yearDivide: 'normal'});
const astrolabe = astro.bySolar('1980-2-14', 0, 'male', true, 'en-US');
const horoscope = astrolabe.horoscope('1980-2-14');
console.log(horoscope.yearly.earthlyBranch);     // shen
```

**Comment by SylarLong** [comment]
Hello @ameurenand , Please upgrade the version to `v2.4.3` and use global configuration `horoscopeDivide: 'normal'` to fix the issue. Thank you for your reporting.

Happy coding~

**Comment by ameurenand** [comment]
It works as expected.
Thank you for this quick hotfix.
