### ISSUE TITLE
错误的排盘 [version]: 2.4.2 iztro.min.js

### ISSUE THREAD

**Issue by MillerTheBest** [SylarLong/iztro#195]
Javascript 调用版本2.4.2 iztro.min.js
这是我目前碰到的唯一一个排盘出问题的生日：农历1958-12-30辰时，女命

换算成代码为：astroMap = iztro.astro.byLunar("1958-12-30L", 4, "女", false, true, 'zh-CN');

代码返回的天盘是（节选）：
solarDate: 1959-2-7                                ---> 正确
lunarDate: 一九五八年腊月三十               ---> 正确
chineseDate: 己亥 丙寅 庚申 庚辰           ---> 正确
body: 天机                                                 ---> 错误
fiveElementsClass: 金四局                       ---> 错误

寅宫为：
* 0: {"index":0,"name":"仆役","isBodyPalace":false,"isOriginalPalace":false,"heavenlyStem":"丙","earthlyBranch":"寅","majorStars":[],"minorStars":[{"name":"铃星","type":"tough","scope":"origin","brightness":"庙"}],"adjectiveStars":[{"name":"天福","type":"adjective","scope":"origin"},{"name":"天月","type":"adjective","scope":"origin"},{"name":"孤辰","type":"adjective","scope":"origin"},{"name":"天伤","type":"adjective","scope":"origin"}],"changsheng12":"绝","boshi12":"病符","jiangqian12":"亡神","suiqian12":"贯索","decadal":{"range":[54,63],"heavenlyStem":"丙","earthlyBranch":"寅"},"ages":[12,24,36,48,60,72,84,96,108,120]}           ---> 错误

大运盘宫命（从寅宫开始）: 命宫,父母,福德,田宅,官禄,仆役,迁移,疾厄,财帛,子女,夫妻,兄弟 | Decadal mutagen: 天同,天机,文昌,廉贞                                          ---> 错误

2016-05-04(丙申) 大限为：丙寅                 ---> 错误

正确的排盘为：
![ziwei pub-iztrolabe](https://github.com/SylarLong/iztro/assets/7899360/1b0a835d-2a62-4a0e-9a2e-4409ee3b35fa)

紫薇派网站上的排盘是正确的，可是代码返回的是错误的。。。
换用阳历生日，代码依旧返回这个错误排盘，不知道是否和当年立春时间有关？希望帮忙检查

**Comment by SylarLong** [comment]
@MillerTheBest 请使用全局参数 yearDivide ，将其设置为 `exact`

```ts
import { astro } from '../../index';

astro.config({ yearDivide: 'exact' });
```
