### ISSUE TITLE
[version]:

### ISSUE THREAD

**Issue by vitasapple** [SylarLong/iztro#197]
子 丑 合化 ⛰️土
寅 亥 合化 🪵木
卯 戌 合化 🔥火
辰 酉 合化 🪙金
巳 申 合化 🌊水
午 未 合化 ⛰️土
这个五形是不是弄错了？子明明是水，辰是木，还是说这个十二地支的归属是紫微特有的？

**Comment by SylarLong** [comment]
你好！@vitasapple  感谢你的关注。
这是地支六合，请参考：https://baike.baidu.com/item/%E5%9C%B0%E6%94%AF%E7%9B%B8%E5%90%88/10152193?fr=ge_ala#1
