### ISSUE TITLE
[version]:2.4.2

### ISSUE THREAD

**Issue by EdwinXiang** [SylarLong/iztro#209]
### 描述（Description）

宫位小限计算有误，和文墨天机的不一样。麻烦检查确认一下

### 版本（Version）

- {version number}

### 重现（Reproduce）

- 调用的方法（funciton name）

  

- 参数（parameters）

  

- 返回值（returns)

**Comment by SylarLong** [comment]
@EdwinXiang 根据你提供的参数，小限排法是没有问题的，之所以出现和文墨不同，是因为你在 https://ziwei.pub 上填写的性别是女，而在文墨上面是男。[参考](https://ziwei.pro/learn/setup.html#_5-%E8%B5%B7%E5%B0%8F%E9%99%90%E8%AF%80)
