### ISSUE TITLE
2.4.4: 天相化忌错误加在天同上

### ISSUE THREAD

**Issue by dna2github** [SylarLong/iztro#212]
### 描述（Description）

https://www.shidianguji.com/book/SDZJ0170/chapter/1jvzop88fh4it?page_from=searching_page&version=7
https://ziwei.pub/astrolabe/?d=1970-11-29&t=0&leap=false&g=male&type=solar&n=
孔子八字，天相化忌；网站上显示是天同化忌
~~并且原书上是土五局，网站上显示火六局~~ (仔细看了下，应该是书上误把生年地支用成命宫地支导致的)

https://ziwei.pub/astrolabe/?d=1980-04-15&t=0&leap=false&g=male&type=solar&n=
孟子八字，天相化忌；网站上显示天同化忌

原书大限从命宫+1开始算，网站上是从命宫开始

**Comment by SylarLong** [comment]
四化版本繁多，所以这个不存在对错。网站目前尚未支持自定义配置四化，之后会加上。至于孔子和孟子的盘，你输入的时间不对，所以不能用来对比。

**Comment by dna2github** [comment]
呃…时间是每60年一个轮回的，你输入年份月份只要对了天干地支是一样的，主要的星都是一样的。
第一个链接是古籍原文的。不过只是在这里提一下。改不改没关系哈。

**Comment by SylarLong** [comment]
@dna2github 感谢大佬
