### ISSUE TITLE
JS不太熟练 演示地址https://a.14star.cn/的代码有吗？想弄来加点星情解析

### ISSUE THREAD

**Issue by lidagogo** [SylarLong/iztro#41]
JS不太熟练 演示地址https://a.14star.cn/的代码有吗？想弄来加点星情解析

**Comment by SylarLong** [comment]
可以去这个仓库看看哦 https://github.com/SylarLong/react-iztro ，虽然还没有写完，但是对于想了解代码来说已经足够了。

1. git clone
2. npm install
3. npm run storybook

然后在浏览器打开storybook的地址就可以看到效果了：http://localhost:6006

happy coding~

**Comment by SylarLong** [comment]
@lidagogo 在集成的时候有任何问题欢迎再来提问。如果觉得对你有用还请给我 `star` 支持一下哦 👍

**Comment by lidagogo** [comment]
感谢 一定支持



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年9月10日(星期天) 晚上6:35
收件人: "SylarLong/iztro";
抄送: "Mention";
主题: Re: [SylarLong/iztro] JS不太熟练 演示地址https://a.14star.cn/的代码有吗？想弄来加点星情解析 (Issue #41)





 
@lidagogo 在集成的时候有任何问题欢迎再来提问。如果觉得对你有用还请给我 star 支持一下哦 👍
 
&mdash;
