### ISSUE TITLE
package.json 里没有找到启动的命令脚本

### ISSUE THREAD

**Issue by zsboss** [SylarLong/iztro#44]
大佬您好，我在package.json 里没有找到启动的命令脚本
![image](https://github.com/SylarLong/iztro/assets/19493235/7b365a94-705d-4b63-a0d3-48c8a9107ed1)

**Comment by SylarLong** [comment]
@zsboss 你好，这是一个library，没有界面的哦，需要你自己启动一个程序，然后import进去，详细集成步骤请查看文档，这是 [传送门](https://docs.iztro.com) 如果想要集成带界面的版本，可以查看 [react-iztro](https://github.com/SylarLong/react-iztro)

happy coding~:)
