### ISSUE TITLE
ziwei.pub footer css 样式问题

### ISSUE THREAD

**Issue by Rokixy** [SylarLong/iztro#61]
### 描述（Description）

页面滚动到最下方后，部分内容被 footer 遮挡
![image](https://github.com/SylarLong/iztro/assets/48944401/906d294b-d16f-4446-aa33-a16db99aca16)

footer 的 `position: fixed;` -> `position: sticky;` 应该可以解决

### 版本（Version）

-

### 环境（Environment）

-

### 重现（Reproduce）

-

**Comment by SylarLong** [comment]
感谢指正，问题已修复🙏
