### ISSUE TITLE
是否支持python调用？

### ISSUE THREAD

**Issue by AQA6666** [SylarLong/iztro#63]
首先感谢您的无私开源，这个仓库对我的帮助很大。
如题，请问目前该库是否支持python调用？
如果支持的话，请问应当如何调用呢？
如果不支持的话，是否在未来有添加python支持的可能性？
期待着您的回复，这对我非常重要，谢谢！

**Comment by SylarLong** [comment]
@AQA6666 

感谢关注，从你的问题来看，应该是想应用在AI上吧？以下是python调用js的方法，希望对你有帮助。因为我对python不熟悉，所以暂时没有将它移植到python上的打算，不过等我把文档写完，这个库稳定以后，可以考虑往其他语言移植

1. 使用Python的execjs库：execjs库允许在Python中执行JavaScript代码。您可以使用该库来调用JavaScript方法。首先，您需要安装execjs库，然后使用execjs.eval()或execjs.compile()方法来执行JavaScript代码。

3. 使用pyv8库：pyv8库是一个Python绑定的V8引擎，它允许您在Python中执行JavaScript代码。您可以使用该库来调用JavaScript方法。

5. 使用PyExecJS库：PyExecJS库是一个Python库，它提供了一个统一的API，可以在多个JavaScript运行时中执行代码，包括Node.js、V8、Rhino等。您可以使用该库来调用JavaScript方法。

**Comment by AQA6666** [comment]
> @AQA6666
> 
> 感谢关注，从你的问题来看，应该是想应用在AI上吧？以下是python调用js的方法，希望对你有帮助。因为我对python不熟悉，所以暂时没有将它移植到python上的打算，不过等我把文档写完，这个库稳定以后，可以考虑往其他语言移植
> 
> 1. 使用Python的execjs库：execjs库允许在Python中执行JavaScript代码。您可以使用该库来调用JavaScript方法。首先，您需要安装execjs库，然后使用execjs.eval()或execjs.compile()方法来执行JavaScript代码。
> 2. 使用pyv8库：pyv8库是一个Python绑定的V8引擎，它允许您在Python中执行JavaScript代码。您可以使用该库来调用JavaScript方法。
> 3. 使用PyExecJS库：PyExecJS库是一个Python库，它提供了一个统一的API，可以在多个JavaScript运行时中执行代码，包括Node.js、V8、Rhino等。您可以使用该库来调用JavaScript方法。

好的，我明白了，感谢您的帮助！
