### ISSUE TITLE
农历阳历转化错误

### ISSUE THREAD

**Issue by SylarLong** [SylarLong/iztro#76]
1996 年 07 月 15 日的农历是丙子年五月三十(鼠年)
算命是农历：一九九六年六月初一
https://ziwei.pub/astrolabe/?d=1996-7-15&t=0&leap=false&g=male&type=solar

来自 v2ex 网友 [totoro625](https://www.v2ex.com/member/totoro625)

Ref. https://www.v2ex.com/t/984778#r_13820187

**Comment by NoManPlay** [comment]
推荐使用https://github.com/6tail/lunar-typescript
这个库里面有较全的农历信息，比自己手写方便一点

**Comment by SylarLong** [comment]
> 推荐使用https://github.com/6tail/lunar-typescript 这个库里面有较全的农历信息，比自己手写方便一点

感谢推荐

**Comment by SylarLong** [comment]
经检查是因为 `1996年` 农历 `六月` 大小月的问题。该问题会导致这一整个月的数据都不对。需要尽快修复。
