### ISSUE TITLE
v2.0.4:horoscope-计算流日不准确

### ISSUE THREAD

**Issue by yushinelee** [SylarLong/iztro#91]
### 版本（Version）

- {version number}

### 重现（Reproduce）

- 调用的方法（funciton name）

  

- 参数（parameters）

  

- 返回值（returns)

**Comment by SylarLong** [comment]
能提供一下参数么？

**Comment by SylarLong** [comment]
由于报告这过长时间无响应，决定关闭此issue，如果集成过程中发现类似问题，请提供参数并reopen这个issue。谢谢~
