### ISSUE TITLE
解盘申请

### ISSUE THREAD

**Issue by chenqi146** [SylarLong/iztro#98]
## 麻烦大佬帮我看下盘, 感谢
<img width="1082" alt="458A202D-60F0-46E8-B813-86C2CC6C3E35" src="https://github.com/SylarLong/iztro/assets/36069431/51693a6e-f465-455f-82a9-a35c7ee6fc65">

### 时辰是否准确
是

### 咨询问题
想了解一下财帛事业婚姻相关的信息

**Comment by SylarLong** [comment]
阁下的命宫主星是 [天同星](https://www.ziwei.pro/learn/major-star.html#%E5%A4%A9%E5%90%8C%E6%98%9F)，还是个文艺青年，对外人热心，对家人包容。从盘上看家庭条件还不错。感情上你其实并不知道自己喜欢什么样的，加上自己被动的个性，所以让感情上变得比较优柔寡断，摇摆不定。由于温和的处事态度，让你在工作中也收获不少助力，但似乎你对自己的工作并不是很满意，所以工作上充满了很多不确定性。在工作中需要选好赛道，不要摇摆不定，这样很难沉淀。财务上你属于风险厌恶型，所以比较没有什么波澜。


仅供参考，不准勿怪，如果不准请参阅 [Wiki](https://github.com/SylarLong/iztro/wiki/%E4%B8%BA%E4%BB%80%E4%B9%88%E6%98%9F%E7%9B%98%E6%98%BE%E7%A4%BA%E7%9A%84%E4%B8%AA%E6%80%A7%E5%92%8C%E6%88%91%E5%AE%9E%E9%99%85%E4%B8%AA%E6%80%A7%E5%B7%AE%E9%82%A3%E4%B9%88%E5%A4%9A%EF%BC%9F)

**Comment by chenqi146** [comment]
谢谢大佬
