### ISSUE TITLE
大佬 帮我看下 谢谢🫡🫡

### ISSUE THREAD

**Issue by EdwardLi-coder** [SylarLong/iztro#99]
### 星盘信息

<img width="1087" alt="image" src="https://github.com/SylarLong/iztro/assets/29945767/7c2bf48f-de8a-44ac-abdd-ea3ba726a1da">

### 时辰是否准确

- [ ] 是

### 咨询问题

想看看事业吧  看看干啥合适

**Comment by SylarLong** [comment]
紫府同宫格，阁下这个盘非常的强势，工作能力很强，眼光长远，大局观强。但是缺点也很明显，会给人非常强的距离感，所以会莫名的感到孤独。需要增进和家人的感情，不要过于关注在自己身上，家庭和小孩同样需要你的关心。和伴侣之间相处很难亲密，比较适合相敬如宾的相处模式。你这个盘大有关照都给了别人，抱怨都给了家里的感觉。

仅供参考，不准勿怪，如果不准请参阅 [Wiki](https://github.com/SylarLong/iztro/wiki/%E4%B8%BA%E4%BB%80%E4%B9%88%E6%98%9F%E7%9B%98%E6%98%BE%E7%A4%BA%E7%9A%84%E4%B8%AA%E6%80%A7%E5%92%8C%E6%88%91%E5%AE%9E%E9%99%85%E4%B8%AA%E6%80%A7%E5%B7%AE%E9%82%A3%E4%B9%88%E5%A4%9A%EF%BC%9F)

**Comment by SylarLong** [comment]
事业上你这是个非常强势的管理格，所以不管从事哪方面行业，都应该会往管理层走的。

**Comment by EdwardLi-coder** [comment]
> 紫府同宫格，阁下这个盘非常的强势，工作能力很强，眼光长远，大局观强。但是缺点也很明显，会给人非常强的距离感，所以会莫名的感到孤独。需要增进和家人的感情，不要过于关注在自己身上，家庭和小孩同样需要你的关心。和伴侣之间相处很难亲密，比较适合相敬如宾的相处模式。你这个盘大有关照都给了别人，抱怨都给了家里的感觉。
> 
> 
> 
> 仅供参考，不准勿怪，如果不准请参阅 [Wiki](https://github.com/SylarLong/iztro/wiki/%E4%B8%BA%E4%BB%80%E4%B9%88%E6%98%9F%E7%9B%98%E6%98%BE%E7%A4%BA%E7%9A%84%E4%B8%AA%E6%80%A7%E5%92%8C%E6%88%91%E5%AE%9E%E9%99%85%E4%B8%AA%E6%80%A7%E5%B7%AE%E9%82%A3%E4%B9%88%E5%A4%9A%EF%BC%9F)

好的，谢谢大佬
